name: key_encrypt
description: A Dart API Client for the Open-Meteo API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  camera: ^0.11.3+1
  cryptography: ^2.9.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  json_annotation: ^4.11.0
  key_api:
    path: ../key_api
  mocktail: ^1.0.4
  mt19937: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.3.1
  test: ^1.16.4
